addon:
    key: anyvendor-atlassian-cloud-jira-sample
    base-url: https://92ac-91-234-128-213.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG

security.ignored: /jwt-myself

spring:
  datasource:
    url: jdbc:h2:file:./db_dev;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update